name: Create Weekly PR from staging to main

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 12:00AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check if staging is ahead of main
      run: |
        git fetch origin

        COMMITS_AHEAD=$(git rev-list --oneline origin/main..origin/staging)
        
        if [ -z "$COMMITS_AHEAD" ]; then
          echo "staging is not ahead of main. No PR should be created."
          echo "staging_ahead=false" >> $GITHUB_OUTPUT
        else
          echo "staging is ahead of main. PR should be created."
          echo "staging_ahead=true" >> $GITHUB_ENV
          echo "commits_ahead=$COMMITS_AHEAD" >> $GITHUB_ENV
        fi

    - name: Create Pull Request
      if: env.staging_ahead
      uses: peter-evans/create-pull-request@v4
      with:
        base: main
        branch: staging
        title: 'Weekly PR from staging to main'
        body: |
          This PR is automatically created by a GitHub Actions Workflow every Monday at 12:00AM UTC.

          Here are the proposed commits to be merged from staging to main:
          ${{ env.commits_ahead }}